extends: '../../.nycrc.yml'
cwd: '../../packages'
reportDir: '../integration/protractor-cucumber/target/coverage'
tempDir: '../.nyc_output'
include:
  - 'core/src/**/*.ts'
  - 'core/lib/**/*.js'
  - 'cucumber/src/**/*.ts'
  - 'cucumber/lib/**/*.js'
  - 'protractor/src/**/*.ts'
  - 'protractor/lib/**/*.js'
  - 'web/src/**/*.ts'
  - 'web/lib/**/*.js'
exclude:
  - '**/target/**'
  - '**/spec/**'
  - '**/*.d.ts'
  - '**/*.spec.ts'
