extends: '../../.nycrc.yml'
cwd: '../../packages'
reportDir: '../integration/mocha/target/coverage'
tempDir: '../.nyc_output'
include:
  - 'core/src/**/*.ts'
  - 'core/lib/**/*.js'
  - 'mocha/src/**/*.ts'
  - 'mocha/lib/**/*.js'
exclude:
  - '**/target/**'
  - '**/spec/**'
  - '**/*.d.ts'
  - '**/*.spec.ts'
